version: '3'

services:
  yunx-bot:
    build: .
    container_name: yunx-bot
    restart: unless-stopped
    volumes:
      - ./downloads:/downloads
      - ./cookies:/cookies
    environment:
      - TELEGRAM_BOT_TOKEN=your_telegram_bot_token_here
      - DOWNLOAD_PATH=/downloads
      - CONVERT_TO_MP4=true
      # 可选配置
      # - PROXY_HOST=http://your-proxy-server:port
      # - X_COOKIES=/cookies/x_cookies.txt
      # - B_COOKIES=/cookies/bilibili_cookies.txt
      # - CUSTOM_DOWNLOAD_PATH=false
      # qBittorrent 配置
      # - QBITTORRENT_HOST=http://qbittorrent:8080
      # - QBITTORRENT_USERNAME=admin
      # - QBITTORRENT_PASSWORD=adminadmin
      # - QBITTORRENT_DOWNLOAD_PATH=/downloads/torrents
    networks:
      - yunx-network

  # 可选：qBittorrent 服务
  # qbittorrent:
  #   image: linuxserver/qbittorrent:latest
  #   container_name: qbittorrent
  #   restart: unless-stopped
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/Shanghai
  #     - WEBUI_PORT=8080
  #   volumes:
  #     - ./config/qbittorrent:/config
  #     - ./downloads/torrents:/downloads
  #   ports:
  #     - "8080:8080"
  #     - "6881:6881"
  #     - "6881:6881/udp"
  #   networks:
  #     - yunx-network

networks:
  yunx-network:
    driver: bridge